### ISSUE TITLE
BUG: EFAULT returned on 32-bit x86 for some tests

### ISSUE THREAD

**Issue by jengelh** [seccomp/libseccomp#32]
Using v2.3.0, some tests fail when seccomp is built with -m32 running on amd64.
```
[  819s]  batch name: 15-basic-resolver
[  819s]  test mode:  c
[  819s]  test type:  basic
[  819s] Test 15-basic-resolver%%001-00001 result:   FAILURE 15-basic-resolver rc=1
[  819s]  batch name: 16-sim-arch_basic
[  819s]  test mode:  c
[  819s]  test type:  bpf-sim
[  819s]  test arch:  x86
[  820s] Test 16-sim-arch_basic%%001-00001 result:   ERROR 16-sim-arch_basic rc=14
[  820s]  test arch:  x86
[  820s] Test 16-sim-arch_basic%%002-00001 result:   ERROR 16-sim-arch_basic rc=14
[  820s]  test arch:  x86
[  820s] Test 16-sim-arch_basic%%003-00001 result:   ERROR 16-sim-arch_basic rc=14
[...]
[  824s] Test 16-sim-arch_basic%%012-00001 result:   ERROR 16-sim-arch_basic rc=14
[  824s]  test mode:  c
[  824s]  test type:  bpf-valgrind
[  829s] Test 16-sim-arch_basic%%013-00001 result:   FAILURE 16-sim-arch_basic rc=14
[  829s]  batch name: 17-sim-arch_merge
[  829s]  test mode:  c
[  829s]  test type:  bpf-sim
[  829s] Test 17-sim-arch_merge%%001-00001 result:   ERROR 17-sim-arch_merge rc=14
[  830s] Test 17-sim-arch_merge%%002-00001 result:   ERROR 17-sim-arch_merge rc=14
[  830s] Test 17-sim-arch_merge%%003-00001 result:   ERROR 17-sim-arch_merge rc=14
[  830s] Test 17-sim-arch_merge%%004-00001 result:   ERROR 17-sim-arch_merge rc=14
[ 1159s] Test 30-sim-socket_syscalls%%015-00001 result:   ERROR 30-sim-socket_syscalls rc=14
[ 1159s]  test mode:  c
[ 1159s]  test type:  bpf-valgrind
[ 1163s] Test 30-sim-socket_syscalls%%016-00001 result:   FAILURE 30-sim-socket_syscalls rc=14
```
```
abuild@ares40:/home/abuild/rpmbuild/BUILD/libseccomp-2.3.0/tests> ./30-sim-socket_syscalls; echo $?
14
abuild@ares40:/home/abuild/rpmbuild/BUILD/libseccomp-2.3.0/tests> ./29-sim-pseudo_syscall ; echo $?
#
# pseudo filter code start
#
# filter for arch x86 (1073741827)
if ($arch == 1073741827)
  # default action
  action ALLOW;
# invalid architecture action
action KILL;
#
# pseudo filter code end
#
0
```
So it does not output anything beyond 14 (EFAULT).

**Comment by pcmoore** [comment]
Thanks for the report, what kernel/kernel-headers are you using to build libseccomp?

I've also just noticed some problems on 32-bit x86 using old kernels that didn't show up when testing against newer kernels; I'm not 100% confident is an old kernel problem, but at first glance it is the most obvious difference.

**Comment by jengelh** [comment]
https://build.opensuse.org/build/security/openSUSE_Factory/i586/libseccomp/_log tells me it is using 4.2 headers with a 4.4 kernel (and does that inside KVM).

**Comment by pcmoore** [comment]
Okay, thanks for the data point.

**Comment by pcmoore** [comment]
I just did some more testing on a current Fedora Rawhide 32-bit x86 system and I still can't reproduce the problem on a Rawhide system, I'm going to try it on an older system next.

**Comment by pcmoore** [comment]
Finally!

On a RHEL-7.x 64-bit x86_64 system with the 32-bit toolchain installed I can reproduce failures in the following tests if I configure the library via 'CFLAGS="-m32" ./configure --enable-prefix=/tmp/seccomp':

* 15-basic-resolver
* 16-sim-arch_basic
* 17-sim-arch_merge
* 30-sim-socket_syscalls

**Comment by pcmoore** [comment]
At least one problem appears to be related to seccomp_syscall_resolve_name() returning the new direct syscall numbers regardless of what the __NR_* defines indicate, this causes problems on systems with old kernel headers that don't include the new direct wired socket syscall defines.  See the 15-basic-resolver test failures for an example.

**Comment by pcmoore** [comment]
Fixing the resolver problem mentioned in the comment above seems to correct the following tests:

* 15-basic-resolver
* 16-sim-arch_basic
* 17-sim-arch_merge

**Comment by pcmoore** [comment]
This should be fixed in 73d83e45efbe8c31067c97155162f17ca51b7435.  I likely be pushing a new stable release sometime this week (or next if I get swamped) with this fix included.

**Comment by jengelh** [comment]
Applying 73d83e4 ontop of 2.3.0, but test 15 still fails with exit status 1. Intentional?

**Comment by pcmoore** [comment]
Not intentional no, there should never been any test failures or errors, some skipped tests are to be expected.

I just re-ran all the tests using my reproducer above and everything came back clean, are you able to do any debugging?

**Comment by pcmoore** [comment]
@jengelh are you able to provide any more info on this?  Without a reproducer I'm somewhat limited in what I can do at this point ...

**Comment by pcmoore** [comment]
Okay, I was able to recreate this on one of my systems, working on it now.

**Comment by jengelh** [comment]
```
(gdb) b main
Breakpoint 1 at 0x80488bc: file 15-basic-resolver.c, line 30.
(gdb) r
Starting program: /home/abuild/rpmbuild/BUILD/libseccomp-2.3.0/tests/15-basic-resolver 
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-7.2.i586

Breakpoint 1, main (argc=1, argv=0xffffda74) at 15-basic-resolver.c:30
30              char *name = NULL;
(gdb) n
32              if (seccomp_syscall_resolve_name("open") != __NR_open)
(gdb) 
34              if (seccomp_syscall_resolve_name("socket") != __NR_socket)
(gdb) si
0x080488df      34              if (seccomp_syscall_resolve_name("socket") != __NR_socket)
(gdb) 
0x080488e4      34              if (seccomp_syscall_resolve_name("socket") != __NR_socket)
(gdb) 
seccomp_syscall_resolve_name (name=0x8053035 "socket") at api.c:304
304     {
(gdb) 
0x0804906a      304     {
(gdb) 
0x0804906c      304     {
(gdb) 
0x0804906d      304     {
(gdb) 
0x08049070      304     {
(gdb) 
0x080494b8 in __x86.get_pc_thunk.ax ()
(gdb) 
0x080494bb in __x86.get_pc_thunk.ax ()
(gdb) 
0x08049075 in seccomp_syscall_resolve_name (name=0x8053035 "socket") at api.c:304
304     {
(gdb) 
305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) 
0x0804907d      305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) 
0x08049080      305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) 
0x08049082      305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) 
0x08049084      305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) 
seccomp_syscall_resolve_name_arch (arch_token=0, name=0x8053035 "socket") at api.c:253
253     {
(gdb) 
0x08048f27      253     {
(gdb) 
0x08048f29      253     {
(gdb) 
0x08048f2a      253     {
(gdb) 
0x08048f2d      253     {
(gdb) 
__x86.get_pc_thunk.bx () at ../sysdeps/i386/crti.S:66
66      ../sysdeps/i386/crti.S: No such file or directory.
(gdb) 
0x080487e3      66      in ../sysdeps/i386/crti.S
(gdb) 
0x08048f32 in seccomp_syscall_resolve_name_arch (arch_token=0, name=0x8053035 "socket") at api.c:253
253     {
(gdb) 
256             if (name == NULL)
(gdb) n
259             if (arch_token == 0)
(gdb) 
260                     arch_token = arch_def_native->token;
(gdb) 
261             if (arch_valid(arch_token))
(gdb) 
263             arch = arch_def_lookup(arch_token);
(gdb) 
264             if (arch == NULL)
(gdb) p arch
$1 = (const struct arch_def *) 0x806cd00 <arch_def_x86>
(gdb) n
267             return arch_syscall_resolve_name(arch, name);
(gdb) si
0x08048f92      267             return arch_syscall_resolve_name(arch, name);
(gdb) 
0x08048f95      267             return arch_syscall_resolve_name(arch, name);
(gdb) 
0x08048f98      267             return arch_syscall_resolve_name(arch, name);
(gdb) 
arch_syscall_resolve_name (arch=0x806cd00 <arch_def_x86>, name=0x8053035 "socket") at arch.c:295
295     {
(gdb) 
0x080515d1      295     {
(gdb) 
0x080515d3      295     {
(gdb) 
0x080515d6      295     {
(gdb) 
0x080494b8 in __x86.get_pc_thunk.ax ()
(gdb) 
0x080494bb in __x86.get_pc_thunk.ax ()
(gdb) 
0x080515db in arch_syscall_resolve_name (arch=0x806cd00 <arch_def_x86>, name=0x8053035 "socket") at arch.c:295
295     {
(gdb) 
296             if (arch->syscall_resolve_name)
(gdb) 
0x080515e3      296             if (arch->syscall_resolve_name)
(gdb) 
0x080515e6      296             if (arch->syscall_resolve_name)
(gdb) 
0x080515e8      296             if (arch->syscall_resolve_name)
(gdb) 
297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
0x080515ed      297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
0x080515f0      297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
0x080515f3      297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
0x080515f6      297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
x86_syscall_resolve_name (name=0x8053035 "socket") at arch-x86-syscalls.c:467
467     {
(gdb) 
0x08051f49      467     {
(gdb) 
0x08051f4b      467     {
(gdb) 
0x08051f4c      467     {
(gdb) 
0x08051f4f      467     {
(gdb) 
__x86.get_pc_thunk.bx () at ../sysdeps/i386/crti.S:66
66      ../sysdeps/i386/crti.S: No such file or directory.
(gdb) 
0x080487e3      66      in ../sysdeps/i386/crti.S
(gdb) 
0x08051f54 in x86_syscall_resolve_name (name=0x8053035 "socket") at arch-x86-syscalls.c:467
467     {
(gdb) 
469             const struct arch_syscall_def *table = x86_syscall_table;
(gdb) n
473             if (strcmp(name, "accept") == 0)
(gdb) 
475             if (strcmp(name, "accept4") == 0)
(gdb) 
477             else if (strcmp(name, "bind") == 0)
(gdb) 
479             else if (strcmp(name, "connect") == 0)
(gdb) 
481             else if (strcmp(name, "getpeername") == 0)
(gdb) 
483             else if (strcmp(name, "getsockname") == 0)
(gdb) 
485             else if (strcmp(name, "getsockopt") == 0)
(gdb) 
487             else if (strcmp(name, "listen") == 0)
(gdb) 
489             else if (strcmp(name, "recv") == 0)
(gdb) 
491             else if (strcmp(name, "recvfrom") == 0)
(gdb) 
493             else if (strcmp(name, "recvmsg") == 0)
(gdb) 
495             else if (strcmp(name, "recvmmsg") == 0)
(gdb) 
497             else if (strcmp(name, "send") == 0)
(gdb) 
499             else if (strcmp(name, "sendmsg") == 0)
(gdb) 
501             else if (strcmp(name, "sendmmsg") == 0)
(gdb) 
503             else if (strcmp(name, "sendto") == 0)
(gdb) 
505             else if (strcmp(name, "setsockopt") == 0)
(gdb) 
507             else if (strcmp(name, "shutdown") == 0)
(gdb) 
509             else if (strcmp(name, "socket") == 0)
(gdb) 
510                     return __PNR_socket;
(gdb) n
520     }
(gdb) p $eax
$2 = -101
(gdb) si
0x0805227b      520     }
(gdb) 
0x0805227c      520     }
(gdb) 
0x080515f8 in arch_syscall_resolve_name (arch=0x806cd00 <arch_def_x86>, name=0x8053035 "socket") at arch.c:297
297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
0x080515fb      297                     return (*arch->syscall_resolve_name)(name);
(gdb) 
300     }
(gdb) 
0x08051603      300     }
(gdb) 
0x08048f9d in seccomp_syscall_resolve_name_arch (arch_token=1073741827, name=0x8053035 "socket") at api.c:267
267             return arch_syscall_resolve_name(arch, name);
(gdb) 
268     }
(gdb) 
0x08048fa3      268     }
(gdb) 
0x08048fa4      268     }
(gdb) 
0x08049089 in seccomp_syscall_resolve_name (name=0x8053035 "socket") at api.c:305
305             return seccomp_syscall_resolve_name_arch(SCMP_ARCH_NATIVE, name);
(gdb) p $eax
$3 = -101
(gdb) si
306     }
(gdb) 
0x0804908f      306     }
(gdb) 
0x08049090      306     }
(gdb) 
0x080488e9 in main (argc=1, argv=0xffffda74) at 15-basic-resolver.c:34
34              if (seccomp_syscall_resolve_name("socket") != __NR_socket)
(gdb) p __NR_socket+0
$4 = 359
```

**Comment by pcmoore** [comment]
Thanks for the help, I think this should finally be fixed with 13e0bae9571c195ee979a66b329aa538b87ee65d.
